CREATE TABLE `system_user` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`username` CHAR(32) NOT NULL,
	`password_sha` CHAR(255) NULL DEFAULT NULL,
	`password_md5` CHAR(255) NULL DEFAULT NULL,
	`email` CHAR(255) NOT NULL,
	`joindate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`locale` CHAR(6) NOT NULL DEFAULT 'enUS',
	`last_active` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`account_flag` INT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1;